# Generated by Django 3.1.5 on 2021-01-31 16:16

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=30)),
                ('doctor_last_name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('phone_number', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('salary', models.FloatField()),
                ('url', models.SlugField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.IntegerField()),
                ('url', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Floor',
                'verbose_name_plural': 'Floors',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=30)),
                ('patient_last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('phone_number', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('sickness', models.CharField(max_length=50)),
                ('url', models.SlugField(max_length=60, unique=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.floor')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
    ]
