# Generated by Django 3.1.5 on 2021-02-01 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210201_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='url',
            new_name='doctor_url',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='url',
            new_name='pacient_url',
        ),
    ]
