# Generated by Django 3.1.5 on 2021-02-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210201_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='medical_speciality',
            field=models.CharField(choices=[('Allergology', 'Allergology'), ('Anesthesiology', 'Anesthesiology'), ('Angiology', 'Angiology'), ('Cardiology', 'Cardiology'), ('Endocrinology', 'Endocrinology'), ('Stomatology', 'Stomatology'), ('Gastroenterology', 'Gastroenterology'), ('Geriatrics', 'Geriatrics'), ('Hematology', 'Hematology'), ('Hepatology', 'Hepatology'), ('Infectology', 'Infectology'), ('Aerospace medicine', 'Aerospace medicine'), ('Sports medicine', 'Sports medicine'), ('Emergency medicine', 'Emergency medicine'), ('Family and community medicine', 'Family and community medicine'), ('Physical medicine and rehabilitation', 'Physical medicine and rehabilitation'), ('Forensic Medicine', 'Forensic Medicine'), ('Intensive medicine', 'Intensive medicine'), ('Internal Medicine', 'Internal Medicine'), ('preventive medicine and public health', 'preventive medicine and public health'), ('Work Medicine', 'Work Medicine'), ('Nephrology', 'Nephrology'), ('Pneumology', 'Pneumology'), ('Neurology', 'Neurology'), ('Nutriology', 'Nutriology'), ('Medical oncology', 'Medical oncology'), ('Radiation Oncology', 'Radiation Oncology'), ('Pediatrics', 'Pediatrics'), ('Psychiatry', 'Psychiatry'), ('Rheumatology', 'Rheumatology'), ('Toxicology', 'Toxicology')], default='ALL', max_length=40),
        ),
        migrations.AlterField(
            model_name='floor',
            name='floor_name',
            field=models.CharField(choices=[('Allergology', 'Allergology'), ('Anesthesiology', 'Anesthesiology'), ('Angiology', 'Angiology'), ('Cardiology', 'Cardiology'), ('Endocrinology', 'Endocrinology'), ('Stomatology', 'Stomatology'), ('Gastroenterology', 'Gastroenterology'), ('Geriatrics', 'Geriatrics'), ('Hematology', 'Hematology'), ('Hepatology', 'Hepatology'), ('Infectology', 'Infectology'), ('Aerospace medicine', 'Aerospace medicine'), ('Sports medicine', 'Sports medicine'), ('Emergency medicine', 'Emergency medicine'), ('Family and community medicine', 'Family and community medicine'), ('Physical medicine and rehabilitation', 'Physical medicine and rehabilitation'), ('Forensic Medicine', 'Forensic Medicine'), ('Intensive medicine', 'Intensive medicine'), ('Internal Medicine', 'Internal Medicine'), ('preventive medicine and public health', 'preventive medicine and public health'), ('Work Medicine', 'Work Medicine'), ('Nephrology', 'Nephrology'), ('Pneumology', 'Pneumology'), ('Neurology', 'Neurology'), ('Nutriology', 'Nutriology'), ('Medical oncology', 'Medical oncology'), ('Radiation Oncology', 'Radiation Oncology'), ('Pediatrics', 'Pediatrics'), ('Psychiatry', 'Psychiatry'), ('Rheumatology', 'Rheumatology'), ('Toxicology', 'Toxicology')], default='ALL', max_length=40),
        ),
    ]
